apiVersion: v1
kind: Service
metadata:
  name: service-appointments
spec:
  selector:
    app: service-appointments
  type: NodePort
  ports:
    - name: http
      port: 8082
      nodePort: 31002

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-appointments
spec:
  selector:
    matchLabels:
      app: service-appointments
  replicas: 1
  template:
    metadata:
      labels:
        app: service-appointments
    spec:
      containers:
        - name: server
          image: boghdanpogulyaka/service-appointments:latest
          ports:
            - name: http
              containerPort: 8082