apiVersion: v1
kind: Service
metadata:
  name: service-barber-feadback
spec:
  selector:
    app: service-barber-feadback
  type: NodePort
  ports:
    - name: http
      port: 8083
      nodePort: 31003

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-barber-feadback
spec:
  selector:
    matchLabels:
      app: service-barber-feadback
  replicas: 1
  template:
    metadata:
      labels:
        app: service-barber-feadback
    spec:
      containers:
        - name: server
          image: boghdanpogulyaka/service-barber-feadback:latest
          ports:
            - name: http
              containerPort: 8083