apiVersion: v1
kind: Service
metadata:
  name: service-barber-services
spec:
  selector:
    app: service-barber-services
  type: NodePort
  ports:
    - name: http
      port: 8081
      nodePort: 30001

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-barber-services
spec:
  selector:
    matchLabels:
      app: service-barber-services
  replicas: 1
  template:
    metadata:
      labels:
        app: service-barber-services
    spec:
      containers:
        - name: server
          image: boghdanpogulyaka/service-barber-services:latest
          ports:
            - name: http
              containerPort: 8081